subject = "Теория вероятностей"
description = "Материалы для подготовки к экзамену"
term = 5 # номер семестра
authors = [
  "Егор Смирнов",
  "Артём Рудяк",
  "Артём Соловьёв",
  "Александр Храмов",
  "Роберт Толстов",
  "Данила Григорьев",
  "Михаил Чертков",
  "Виктория Лазарева",
  "Вадим Карасёв",
  "Артём Кудяков",
  "Радомир Тюменцев",
  "Александр Железко",
  "Иван Архипов",
  "Михаил Леонтьев",
  "Маргарита Потапкина"
]

[sections]
numbering = true
prefix = "Вопрос"
sections = [
  "Сходимость последовательностей случайных величин (по вероятности, почти наверное, в среднем, по распределению).",
  "Теорема о связи между сходимостью в среднем и по вероятности.",
  "Теорема о связи между сходимостями по вероятности, в среднем, по распределению.",
  "Теорема о связи между сходимостью по вероятности и сходимостью к константе по распределению.",
  "Определение закона больших чисел.",
  "Теорема ЗБЧ для н.о.р. величин.",
  "Центральная предельная теорема.",
  "Генеральная и выборочная совокупности, объём выборки, вариационный ряд, варианта, частота",
  "Виды вариационных рядов",
  "Гистограмма, полигон",
  "Формулы числовых характеристик.",
  "Эмпирическая функция распределения(эфр)",
  "Свойства эфр",
  "Понятия статистики, оценки, выборочной характеристики",
  "Несмещенные, состоятельные и эффективные оценки",
  "Теорема о единственности эффективной оценки.",
  "Определение регулярной параметрической модели.",
  "Неравенство рао-крамера.",
  "Информация по фишеру",
  "Построение эффективной по рао-крамеру оценки для пуассоновского распределения.",
  "Теорема о несмещенной и состоятельной оценке математического ожидания",
  "Теорема об эффективной оценке математического ожидания",
  "Теорема о несмещенной и состоятельной оценке функции распределения.",
  "Теорема о несмещенной оценке дисперсии",
  "Метод максимального правдоподобия и метод моментов. функция правдоподобия",
  "Применение методов ммп к построению оценок параметров нормального и биномиального распределений",
  "Применение методов мм к построению оценок параметров нормального и биномиального распределений",
  "Доверительное оценивание. Постановка задачи, определение доверительного интервала, доверительная вероятность.",
  "Лемма фишера",
  "Распределения стьюдента, хи-квадрат, формулы для построения этих сл. величин",
  "Построение доверительных интервалов для параметра а нормального распределения при известном и неизвестном σ",
  "Определение статистической гипотезы, критерия,  ошибок первого и второго рода, уровня значимости, мощности критерия, критической области",
  "Критерий неймана-пирсона",
  "Построение оптимального критерия неймана-пирсона  для параметра а нормального распределения для двух простых гипотез.",
  "Построение оптимального критерия неймана-пирсона для двух простых гипотез для параметра показательного распределения",
  "Проверка сложных гипотез",
  "Проверка простой гипотезы h0  против сложной h1",
  "Критерии согласия. критерий  χ2  и критерий колмогорова",
  "Регрессионный анализ. Постановка задачи.",
  "Построение выборочного уравнения регрессии.",
  "Выборочный коэффициент корреляции, его свойства",
  "Проверка гипотезы о значимости выборочного коэффициента корреляции",
  "Теорема гаусса-маркова.",
  "Статистические свойства мнк оценок.",
  "Анализ вариации.",
]

